# ============================================================================
# scripts/03_analysis.R
# ============================================================================
# Description:
#   Analysis script to perform basic statistical analysis and data
#   exploration on the generated synthetic dataset.
#
# Author: GPI Workshop 4
# Date: 2026-02-22
# ============================================================================

# ============================================================================
# Initial Configuration and Data Loading
# ============================================================================

# Create 'results' directory if it does not exist
if (!dir.exists("results")) {
  dir.create("results", recursive = TRUE)
}

# Load raw data generated by 01_simulation.R
datos <- read.csv("data/raw/datos_raw.csv")
cat("\n=== START: Data Analysis ===\n")
cat(sprintf("✓ Data loaded: data/raw/datos_raw.csv\n"))
cat(sprintf("  Dimensions: %d rows × %d columns\n\n", nrow(datos), ncol(datos)))

# ============================================================================
# Basic Summary Statistics
# ============================================================================

cat("Summary Statistics for Continuous Variables:\n")
cat("─────────────────────────────────────────────\n")

# Variable x statistics
cat("\nVariable 'x':\n")
cat(sprintf("  Count: %d\n", nrow(datos)))
cat(sprintf("  Mean: %.2f\n", mean(datos$x)))
cat(sprintf("  Median: %.2f\n", median(datos$x)))
cat(sprintf("  Std Dev: %.2f\n", sd(datos$x)))
cat(sprintf("  Min: %.2f | Max: %.2f\n", min(datos$x), max(datos$x)))

# Variable y statistics
cat("\nVariable 'y':\n")
cat(sprintf("  Count: %d\n", nrow(datos)))
cat(sprintf("  Mean: %.2f\n", mean(datos$y)))
cat(sprintf("  Median: %.2f\n", median(datos$y)))
cat(sprintf("  Std Dev: %.2f\n", sd(datos$y)))
cat(sprintf("  Min: %.2f | Max: %.2f\n", min(datos$y), max(datos$y)))

# Variable z statistics
cat("\nVariable 'z':\n")
cat(sprintf("  Count: %d\n", nrow(datos)))
cat(sprintf("  Mean: %.2f\n", mean(datos$z)))
cat(sprintf("  Median: %.2f\n", median(datos$z)))
cat(sprintf("  Std Dev: %.2f\n", sd(datos$z)))
cat(sprintf("  Min: %.2f | Max: %.2f\n", min(datos$z), max(datos$z)))

# ============================================================================
# Correlation Analysis
# ============================================================================

cat("\n\nCorrelation Matrix:\n")
cat("─────────────────────────────────────────────\n")
correlacion <- cor(datos[, c("x", "y", "z")])
print(round(correlacion, 3))

# ============================================================================
# Categorical Variable Analysis
# ============================================================================

cat("\n\nDistribution of Categorical Variable 'grupo':\n")
cat("─────────────────────────────────────────────\n")
tabla_grupo <- table(datos$grupo)
print(tabla_grupo)

# ============================================================================
# Summary Table Export
# ============================================================================

cat("\n\nGenerating Summary Table...\n")

# Create comprehensive summary statistics table
resumen <- data.frame(
  Variable = c("x", "y", "z"),
  N = c(nrow(datos), nrow(datos), nrow(datos)),
  Mean = c(mean(datos$x), mean(datos$y), mean(datos$z)),
  Median = c(median(datos$x), median(datos$y), median(datos$z)),
  SD = c(sd(datos$x), sd(datos$y), sd(datos$z)),
  Min = c(min(datos$x), min(datos$y), min(datos$z)),
  Max = c(max(datos$x), max(datos$y), max(datos$z))
)

# Create output directory for tables
out_dir <- "results/tables"
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
}

# Save summary statistics table
out_path <- file.path(out_dir, "summary_statistics.csv")
write.csv(resumen, out_path, row.names = FALSE)
cat(sprintf("✓ Summary table saved: %s\n", out_path))

# Save correlation matrix
cor_path <- file.path(out_dir, "correlation_matrix.csv")
write.csv(round(correlacion, 3), cor_path)
cat(sprintf("✓ Correlation matrix saved: %s\n", cor_path))

# ============================================================================
# Session Summary
# ============================================================================

cat("\n=== END: Analysis completed successfully ===\n\n")