# ============================================================================
# scripts/03_analisis.R
# ============================================================================
# Description:
#   Advanced statistical analysis script with LaTeX-formatted tables
#   Includes descriptive statistics, correlation analysis, regression,
#   ANOVA, normality tests, and group comparisons.
#
# Author: GPI Workshop 4
# Date: 2026-02-22
# ============================================================================

# ============================================================================
# Initial Configuration and Libraries
# ============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(janitor)
  library(broom)
  library(knitr)
})

# Create 'results' directory if it does not exist
if (!dir.exists("results")) {
  dir.create("results", recursive = TRUE)
}

# Create tables directory
if (!dir.exists("results/tables")) {
  dir.create("results/tables", recursive = TRUE)
}

# Load raw data generated by 01_simulation.R
datos <- read.csv("data/raw/datos_raw.csv")
cat("\n╔════════════════════════════════════════════════╗\n")
cat("║        ADVANCED DATA ANALYSIS REPORT         ║\n")
cat("╚════════════════════════════════════════════════╝\n\n")
cat(sprintf("✓ Data loaded: data/raw/datos_raw.csv\n"))
cat(sprintf("  Dimensions: %d rows × %d columns\n", nrow(datos), ncol(datos)))
cat(sprintf("  Variables: %s\n\n", paste(names(datos), collapse = ", ")))

# ============================================================================
# 1. COMPREHENSIVE DESCRIPTIVE STATISTICS
# ============================================================================

cat("\n┌─ 1. DESCRIPTIVE STATISTICS ─────────────────────────────────┐\n")

# Select numeric variables
numeric_vars <- c("x", "y", "z")

# Function to calculate extended statistics
desc_stats <- function(variable) {
  data.frame(
    Variable = variable,
    N = length(na.omit(datos[[variable]])),
    Mean = mean(datos[[variable]], na.rm = TRUE),
    SD = sd(datos[[variable]], na.rm = TRUE),
    Median = median(datos[[variable]], na.rm = TRUE),
    Q1 = quantile(datos[[variable]], 0.25, na.rm = TRUE),
    Q3 = quantile(datos[[variable]], 0.75, na.rm = TRUE),
    IQR = IQR(datos[[variable]], na.rm = TRUE),
    Min = min(datos[[variable]], na.rm = TRUE),
    Max = max(datos[[variable]], na.rm = TRUE),
    Range = max(datos[[variable]], na.rm = TRUE) - min(datos[[variable]], na.rm = TRUE),
    Skewness = (mean(datos[[variable]], na.rm = TRUE) - median(datos[[variable]], na.rm = TRUE)) / sd(datos[[variable]], na.rm = TRUE),
    CV = (sd(datos[[variable]], na.rm = TRUE) / mean(datos[[variable]], na.rm = TRUE)) * 100,
    row.names = NULL
  )
}

# Create comprehensive summary
resumen_detallado <- bind_rows(lapply(numeric_vars, desc_stats))

# Display summary
cat("\nDetailed Summary Statistics:\n")
print(resumen_detallado %>% arrange(Variable))

# ============================================================================
# 2. CORRELATION ANALYSIS
# ============================================================================

cat("\n┌─ 2. CORRELATION ANALYSIS ──────────────────────────────────┐\n")

# Pearson correlation
correlation_matrix <- cor(datos[numeric_vars])
cat("\nPearson Correlation Matrix:\n")
print(round(correlation_matrix, 4))

# Correlation with p-values function
cor_pvalue <- function(var1, var2) {
  result <- cor.test(datos[[var1]], datos[[var2]])
  data.frame(
    Var1 = var1,
    Var2 = var2,
    Correlation = round(result$estimate, 4),
    P.value = format(result$p.value, scientific = TRUE, digits = 4),
    Sig = ifelse(result$p.value < 0.001, "***", 
                 ifelse(result$p.value < 0.01, "**", 
                        ifelse(result$p.value < 0.05, "*", "ns")))
  )
}

# Calculate all pairwise correlations
combinations <- combn(numeric_vars, 2)
cor_pvalues <- bind_rows(apply(combinations, 2, function(pair) {
  cor_pvalue(pair[1], pair[2])
}))

cat("\nCorrelation with P-values:\n")
print(cor_pvalues)

# ============================================================================
# 3. GROUP ANALYSIS
# ============================================================================

cat("\n┌─ 3. GROUP ANALYSIS ────────────────────────────────────────┐\n")

# Group distribution
cat("\nGroup Distribution:\n")
grupo_dist <- table(datos$grupo)
print(grupo_dist)

# Descriptive statistics by group
group_stats <- datos %>%
  group_by(grupo) %>%
  summarise(
    N = n(),
    x_mean = mean(x, na.rm = TRUE),
    x_sd = sd(x, na.rm = TRUE),
    y_mean = mean(y, na.rm = TRUE),
    y_sd = sd(y, na.rm = TRUE),
    z_mean = mean(z, na.rm = TRUE),
    z_sd = sd(z, na.rm = TRUE),
    .groups = 'drop'
  )

cat("\nMean and SD by Group:\n")
print(group_stats)

# ============================================================================
# 4. NORMALITY TESTS
# ============================================================================

cat("\n┌─ 4. NORMALITY TESTS (Shapiro-Wilk) ────────────────────────┐\n")

normality_tests <- bind_rows(lapply(numeric_vars, function(var) {
  if (length(datos[[var]]) <= 5000) {
    test_result <- shapiro.test(datos[[var]])
    data.frame(
      Variable = var,
      W_statistic = round(test_result$statistic, 6),
      P.value = format(test_result$p.value, scientific = TRUE, digits = 4),
      Normal = ifelse(test_result$p.value > 0.05, "Yes (p > 0.05)", "No (p < 0.05)")
    )
  } else {
    data.frame(
      Variable = var,
      W_statistic = NA,
      P.value = NA,
      Normal = "Sample too large (n > 5000)"
    )
  }
}))

print(normality_tests)

# ============================================================================
# 5. LINEAR REGRESSION ANALYSIS
# ============================================================================

cat("\n┌─ 5. LINEAR REGRESSION MODELS ──────────────────────────────┐\n")

# Model 1: y as function of x
cat("\n--- Model 1: y ~ x ---\n")
lm1 <- lm(y ~ x, data = datos)
summary_lm1 <- summary(lm1)
print(summary_lm1)

# Model 2: z as function of x and y
cat("\n--- Model 2: z ~ x + y ---\n")
lm2 <- lm(z ~ x + y, data = datos)
summary_lm2 <- summary(lm2)
print(summary_lm2)

# Extract regression coefficients for table
coef_table1 <- tidy(lm1) %>%
  mutate(across(where(is.numeric), ~ round(., 6)))

coef_table2 <- tidy(lm2) %>%
  mutate(across(where(is.numeric), ~ round(., 6)))

# ============================================================================
# 6. ANOVA ANALYSIS
# ============================================================================

cat("\n┌─ 6. ANALYSIS OF VARIANCE (ANOVA) ──────────────────────────┐\n")

# Test if groups differ on continuous variables
anova_tests <- bind_rows(lapply(numeric_vars, function(var) {
  anova_result <- aov(datos[[var]] ~ datos$grupo)
  anova_summary <- summary(anova_result)[[1]]
  
  data.frame(
    Variable = var,
    F_statistic = round(anova_summary$"F value"[1], 4),
    P.value = format(anova_summary$"Pr(>F)"[1], scientific = TRUE, digits = 4),
    Significant = ifelse(anova_summary$"Pr(>F)"[1] < 0.05, "Yes *", "No")
  )
}))

cat("\nANOVA Results (Variables by Group):\n")
print(anova_tests)

# ============================================================================
# 7. EXPORT TO CSV (for reference)
# ============================================================================

cat("\n┌─ 7. EXPORTING RESULTS ─────────────────────────────────────┐\n")

out_dir <- "results/tables"

# Save detailed summary statistics
write.csv(resumen_detallado, 
          file.path(out_dir, "summary_statistics_detailed.csv"), 
          row.names = FALSE)
cat("✓ summary_statistics_detailed.csv\n")

# Save correlation matrix
write.csv(round(correlation_matrix, 4), 
          file.path(out_dir, "correlation_matrix_detailed.csv"))
cat("✓ correlation_matrix_detailed.csv\n")

# Save correlation with p-values
write.csv(cor_pvalues, 
          file.path(out_dir, "correlation_pvalues.csv"), 
          row.names = FALSE)
cat("✓ correlation_pvalues.csv\n")

# Save group statistics
write.csv(group_stats, 
          file.path(out_dir, "group_statistics.csv"), 
          row.names = FALSE)
cat("✓ group_statistics.csv\n")

# Save ANOVA results
write.csv(anova_tests, 
          file.path(out_dir, "anova_results.csv"), 
          row.names = FALSE)
cat("✓ anova_results.csv\n")

# Save regression coefficients
write.csv(coef_table1, 
          file.path(out_dir, "regression_model1_coefficients.csv"), 
          row.names = FALSE)
cat("✓ regression_model1_coefficients.csv\n")

write.csv(coef_table2, 
          file.path(out_dir, "regression_model2_coefficients.csv"), 
          row.names = FALSE)
cat("✓ regression_model2_coefficients.csv\n")

# ============================================================================
# 8. EXPORT TO LATEX FORMAT
# ============================================================================

cat("\n┌─ 8. GENERATING LATEX TABLES ───────────────────────────────┐\n")

# Function to create LaTeX table
create_latex_table <- function(df, caption, label, filename) {
  latex_code <- knitr::kable(df, format = "latex", 
                             longtable = TRUE, 
                             booktabs = TRUE,
                             escape = FALSE)
  
  # Add caption and label
  latex_code <- paste0(
    "\\begin{table}[h!]\n",
    "\\centering\n",
    "\\caption{", caption, "}\n",
    "\\label{tab:", label, "}\n",
    latex_code,
    "\n\\end{table}"
  )
  
  writeLines(latex_code, file.path(out_dir, filename))
  return(invisible(NULL))
}

# 8.1 Descriptive Statistics Table
desc_stats_latex <- resumen_detallado %>%
  mutate(across(where(is.numeric), ~ round(., 3)))

latex_desc <- knitr::kable(desc_stats_latex, format = "latex", booktabs = TRUE)
writeLines(latex_desc, file.path(out_dir, "table_descriptive_statistics.tex"))
cat("✓ table_descriptive_statistics.tex\n")

# 8.2 Correlation Matrix Table
cor_latex <- knitr::kable(round(correlation_matrix, 3), 
                          format = "latex", booktabs = TRUE)
writeLines(cor_latex, file.path(out_dir, "table_correlation_matrix.tex"))
cat("✓ table_correlation_matrix.tex\n")

# 8.3 Group Statistics Table
group_stats_latex <- group_stats %>%
  mutate(across(where(is.numeric), ~ round(., 3)))

group_latex <- knitr::kable(group_stats_latex, 
                            format = "latex", booktabs = TRUE)
writeLines(group_latex, file.path(out_dir, "table_group_statistics.tex"))
cat("✓ table_group_statistics.tex\n")

# 8.4 Regression Model 1 - Coefficients
coef_latex1 <- coef_table1 %>%
  rename("Term" = term, 
         "Estimate" = estimate,
         "Std. Error" = std.error,
         "t value" = statistic,
         "Pr(>|t|)" = p.value)

reg1_latex <- knitr::kable(coef_latex1, 
                           format = "latex", booktabs = TRUE)
writeLines(reg1_latex, file.path(out_dir, "table_regression_model1.tex"))
cat("✓ table_regression_model1.tex\n")

# 8.5 Regression Model 2 - Coefficients
coef_latex2 <- coef_table2 %>%
  rename("Term" = term, 
         "Estimate" = estimate,
         "Std. Error" = std.error,
         "t value" = statistic,
         "Pr(>|t|)" = p.value)

reg2_latex <- knitr::kable(coef_latex2, 
                           format = "latex", booktabs = TRUE)
writeLines(reg2_latex, file.path(out_dir, "table_regression_model2.tex"))
cat("✓ table_regression_model2.tex\n")

# 8.6 ANOVA Results Table
anova_latex <- knitr::kable(anova_tests, 
                           format = "latex", booktabs = TRUE)
writeLines(anova_latex, file.path(out_dir, "table_anova_results.tex"))
cat("✓ table_anova_results.tex\n")

# ============================================================================
# 9. CREATE A COMPREHENSIVE LATEX DOCUMENT TEMPLATE
# ============================================================================

cat("\n┌─ 9. GENERATING LATEX DOCUMENT ─────────────────────────────┐\n")

latex_document <- "% Analysis Results - LaTeX Document
% Generated automatically by 03_analisis.R

\\documentclass[11pt,a4paper]{article}
\\usepackage[utf-8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage[spanish]{babel}
\\usepackage{booktabs}
\\usepackage{float}
\\usepackage{longtable}
\\usepackage{array}
\\usepackage{multirow}
\\usepackage{amsmath}

\\title{Statistical Analysis Report}
\\author{GPI Workshop 4}
\\date{\\today}

\\begin{document}
\\maketitle

\\section{Descriptive Statistics}

This section presents comprehensive descriptive statistics for all continuous variables in the dataset.

\\input{table_descriptive_statistics.tex}

\\section{Correlation Analysis}

The following table shows the Pearson correlation coefficients between variables.

\\input{table_correlation_matrix.tex}

\\section{Group Analysis}

Means and standard deviations by group are presented in the following table.

\\input{table_group_statistics.tex}

\\section{Regression Analysis}

\\subsection{Model 1: y ~ x}

\\input{table_regression_model1.tex}

\\subsection{Model 2: z ~ x + y}

\\input{table_regression_model2.tex}

\\section{ANOVA Results}

\\input{table_anova_results.tex}

\\end{document}"

writeLines(latex_document, file.path(out_dir, "Analysis_Report.tex"))
cat("✓ Analysis_Report.tex (Complete LaTeX document template)\n")

# ============================================================================
# 10. SUMMARY AND SESSION INFO
# ============================================================================

cat("\n╔════════════════════════════════════════════════╗\n")
cat("║          ANALYSIS COMPLETED SUCCESSFULLY      ║\n")
cat("╚════════════════════════════════════════════════╝\n\n")

cat("Generated Files (CSV & LaTeX):\n")
cat("  Location: results/tables/\n\n")

cat("CSV Files:\n")
cat("  • summary_statistics_detailed.csv\n")
cat("  • correlation_matrix_detailed.csv\n")
cat("  • correlation_pvalues.csv\n")
cat("  • group_statistics.csv\n")
cat("  • anova_results.csv\n")
cat("  • regression_model1_coefficients.csv\n")
cat("  • regression_model2_coefficients.csv\n\n")

cat("LaTeX Tables (.tex):\n")
cat("  • table_descriptive_statistics.tex\n")
cat("  • table_correlation_matrix.tex\n")
cat("  • table_group_statistics.tex\n")
cat("  • table_regression_model1.tex\n")
cat("  • table_regression_model2.tex\n")
cat("  • table_anova_results.tex\n\n")

cat("LaTeX Document:\n")
cat("  • Analysis_Report.tex (Complete template document)\n\n")

cat("Compilation tip for LaTeX:\n")
cat("  pdflatex Analysis_Report.tex\n\n")