# ============================================================================
# scripts/04_plots.R
# ============================================================================
# Description:
#   Plotting script to generate visualizations from the raw data.
#
# Author: Julio Gómez
# Date: 2026-02-22
# ============================================================================

# ============================================================================
# Initial Configuration
# ============================================================================
source("scripts/packages.R")
cat("\n=== START: Generating Plots ===\n")

# Load raw data generated by 01_simulation.R
data_path <- "data/processed/datos_processed.csv"
if (!file.exists(data_path)) {
  stop(sprintf("ERROR: Data file not found: %s\n", data_path))
}

datos <- read.csv(data_path)
cat(sprintf("✓ Data loaded: %s\n", data_path))

# Create output directory for figures
out_dir <- "results/figures"
if (!dir.exists(out_dir)) {
  dir.create(out_dir, recursive = TRUE)
  cat(sprintf("✓ Directory created: %s\n", out_dir))
}

# ============================================================================
# Histogram of Variable 'z'
# ============================================================================

cat("\nGenerating histogram of variable 'z'...\n")
png(file.path(out_dir, "histogram_z.png"), width = 800, height = 600)
hist(datos$z, 
     main = "Distribution of Variable 'z'", 
     xlab = "z", 
     ylab = "Frequency",
     col = "darkorange",
     border = "#333333")
dev.off()
cat("✓ Histogram saved: results/figures/histogram_z.png\n")

# ============================================================================
# Scatter Plot: Relationship between x and y
# ============================================================================

cat("\nGenerating scatter plot of x vs y with regression line...\n")
png(file.path(out_dir, "scatter_x_y.png"), width = 800, height = 600)
plot(datos$x, datos$y, 
     main = "Relationship: x vs y", 
     xlab = "x", 
     ylab = "y",
     pch = 16,
     col = "#6A44C7",
     cex = 0.7)
# Add linear regression line
abline(lm(y ~ x, data = datos), col = "#00A86B", lwd = 2)
dev.off()
cat("✓ Scatter plot saved: results/figures/scatter_x_y.png\n")

# ============================================================================
# Summary
# ============================================================================

cat("\n✓ All plots generated successfully\n")
cat("=== END: Plot generation completed ===\n\n")